---
version: '3.7'
services:
  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    expose:
      - 4005
    container_name: totta_front
    restart: always
    networks:
      - proxy
networks:
  proxy:
    external: true